### ISSUE TITLE
"&" the url parameter after & is considered to be the tool command and hence error. Kindly help to overcome this issue

### ISSUE THREAD

**Issue by jatinsi** [zrrrzzt/wcag-validator#1]
![wcag-error](https://cloud.githubusercontent.com/assets/17014984/16425239/3aac5156-3d29-11e6-90b6-0c3b86871b6c.png)

**Comment by zrrrzzt** [comment]
Hi

This module is kind of discontinued. 

I've participated in this https://www.npmjs.com/package/wcag project as a replacement. Please try the new module and if it still fails leave an issue in the tracker https://github.com/cfpb/node-wcag/issues

**Comment by jatinsi** [comment]
Do we have an alternative to this?

**Comment by zrrrzzt** [comment]
Yes. https://github.com/cfpb/node-wcag is an alternative to this module.

However, your problem can be solved by encapsulating or escaping the url.

This will not work
```wcag-validator http://www.telemark.no/search?basicsearch%5Bterm%5D=skole&page=3 --id=<api-key>```

This will work
```wcag-validator "http://www.telemark.no/search?basicsearch%5Bterm%5D=skole&page=3" --id=<api-key>```

This will work as well
```wcag-validator http://www.telemark.no/search\?basicsearch%5Bterm%5D\=skole\&page\=3 --id=<api-key>```

**Comment by jatinsi** [comment]
Thanks for your quick replies. Appreciate the help :)
